apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applicationset-mgmt
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/muecahit94/gitops-at-scale.git
      revision: HEAD
      files:
      - path: applicationset/files/configs/*.json
  template:
    metadata:
      name: '{{name}}'
    spec:
      project: 'default'
      source:
        repoURL: https://github.com/muecahit94/gitops-at-scale.git
        targetRevision: HEAD
        path: 'applicationset/files/deployments/{{name}}'
        kustomize:
          images:
            - '{{image}}:{{tag}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true