apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applicationset-mgmt
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/muecahit94/gitops-at-scale.git
      revision: HEAD
      directories:
      - path: applicationset/directory-gen/mgmt/*
  template:
    metadata:
      name: '{{.path.basename}}'
    spec:
      project: 'default'
      source:
        repoURL: https://github.com/muecahit94/gitops-at-scale.git
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.path.basename}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true